kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: couchdb-peer0-org1-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: couchdb-peer1-org1-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
