apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ca
  template:
    metadata:
      labels:
        component: ca
    spec:
      containers:
        - name: ca
          image: hyperledger/fabric-ca
          env: 
            - name:  FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name:  FABRIC_CA_SERVER_CA_NAME
              value: ca
            - name:  FABRIC_CA_SERVER_TLS_ENABLED
              value: "false"
            # - name:  FABRIC_CA_SERVER_TLS_CERTFILE
            #   value: $tlsCert
            # - name:  FABRIC_CA_SERVER_TLS_KEYFILE
            #   value: $tlsKey
          ports:
            - containerPort: 7054
          command: ["sh"]
          args: ["-c", "fabric-ca-server start -b admin:adminpw -d"]
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: crypto-config-artifacts-volume
      volumes:
        - hostPath:
             path: /root/Hyperledger_K8S_POC/crypto-config/peerOrganizations/org1.example.com/ca
           name: crypto-config-artifacts-volume
          