apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer
spec:
  replicas: 1  
  selector:
    matchLabels:
      component: orderer
  template:
    metadata:
      labels:
        component: orderer
    spec:
      containers:
      - name: orderer
        image: hyperledger/fabric-orderer
        env:
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /var/hyperledger/orderer/orderer.genesis.block
        - name: ORDERER_GENERAL_LOCALMSPID
          value: OrdererMSP
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /var/hyperledger/orderer/msp
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "false"
        #- name: ORDERER_GENERAL_TLS_PRIVATEKEY
        #  value: /var/hyperledger/orderer/tls/server.key
        #- name: ORDERER_GENERAL_TLS_CERTIFICATE
        #  value: /var/hyperledger/orderer/tls/server.crt
        #- name: ORDERER_GENERAL_TLS_ROOTCAS
        #  value: '[/var/hyperledger/orderer/tls/ca.crt]'
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric
        ports:
         - containerPort: 7050
        command: ["orderer"]
        volumeMounts:
         - mountPath: /var/hyperledger/orderer/msp 
           name: certificate
           #subPath: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp
           #subPath: orderers/orderer.example.com/msp
        # - mountPath: /var/hyperledger/orderer/tls
        #   name: certificate
        #   #subPath: crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/
        #   subPath: $tlsPath
         - mountPath: /var/hyperledger/orderer/orderer.genesis.block
           name: genesis-block-volume
      volumes:
        - hostPath:
            path: /root/Hyperledger_K8S_POC/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp
          name: orderer-msp-volume
        - hostPath:
            path: /root/Hyperledger_K8S_POC/channel-artifacts/genesis.block
          name: genesis-block-volume
           #path: /opt/share
         #persistentVolumeClaim:
         #  claimName: nfs