apiVersion: v1
kind: Service
metadata:
  name: peer0-node-port
spec:
  type: NodePort
  selector:
    component: peer0-org1
  ports:
    - name: couchdb
      port: 5984
      targetPort: 5984
      nodePort: 31515
    - name: peer0-external-listening-endpoint
      port: 7051
      targetPort: 7051
      nodePort: 31518
    - name: peer0-chaincode-listening-endpoint
      port: 7052
      targetPort: 7052
      nodePort: 31519
    - name: peer0-port3
      port: 7053
      targetPort: 7053
      nodePort: 31520
