apiVersion: v1
kind: Service
metadata:
  name: peer1-org2
spec:
  type: NodePort
  selector:
    component: peer1-org2
  ports:
    - name: couchdb
      port: 5984
      targetPort: 5984
      nodePort: 31529
    - name: peer1-org2-external-listening-endpoint
      port: 7051
      targetPort: 7051
      nodePort: 31530
    - name: peer1-org2-chaincode-listening-endpoint
      port: 7052
      targetPort: 7052
      nodePort: 31531
    - name: peer1-org2-port3
      port: 7053
      targetPort: 7053
      nodePort: 31532
