apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-org1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peer0-org1
  template:
    metadata:
      labels:
        component: peer0-org1
    spec:
      hostname: peer0-org1-node-port
      containers:
        - name: couchdb0
          image: hyperledger/fabric-couchdb
          ports:
            - containerPort: 5984
          env:
            - name: COUCHDB_USER
              value:
            - name: COUCHDB_PASSWORD
              value:
              #valueFrom:
              #  secretKeyRef:
              #    name: couch-db-secret
              #    key: COUCHDB_PASSWORD
          volumeMounts:
            - mountPath: /opt/couchdb
              name: couchdb-storage
        - name: peer0-org1
          image: hyperledger/fabric-peer
          env:
          - name: CORE_LEDGER_STATE_STATEDATABASE
            value: "CouchDB"
          - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
            value: "localhost:5984"
          - name: CORE_VM_ENDPOINT
            value: "http://localhost:2375"
          - name: CORE_LOGGING_LEVEL
            value: "DEBUG"
          - name: CORE_PEER_TLS_ENABLED
            value: "false"
          - name: CORE_PEER_GOSSIP_USELEADERELECTION
            value: "true"
          - name: CORE_PEER_GOSSIP_ORGLEADER
            value: "false" 
          - name: CORE_PEER_PROFILE_ENABLED
            value: "true"
          #- name: CORE_PEER_TLS_CERT_FILE
          #  value: "/etc/hyperledger/fabric/tls/server.crt" 
          #- name: CORE_PEER_TLS_KEY_FILE
          #  value: "/etc/hyperledger/fabric/tls/server.key"
          #- name: CORE_PEER_TLS_ROOTCERT_FILE
          #  value: "/etc/hyperledger/fabric/tls/ca.crt"
          - name: CORE_PEER_ID
            value: peer0-org1-node-port:7051
          - name: CORE_PEER_ADDRESS
            value: peer0-org1-node-port:7051
          - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
            value: peer0-org1-node-port:7051
          - name: CORE_PEER_LOCALMSPID
            value: Org1MSP
          - name: CORE_PEER_CHAINCODELISTENADDRESS
            value: 0.0.0.0:7052
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          ports:
          - containerPort: 7051
          - containerPort: 7052
          - containerPort: 7053
          command: ["peer"]
          args: ["node","start"]
          volumeMounts:
            #- mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts 
            #  name: certificate
            #  subPath: channel-artifacts
            - mountPath: /etc/hyperledger/fabric/msp
              name: peer0-org1-msp-volume
              #subPath: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1-node-port/msp
            #- mountPath: /etc/hyperledger/fabric/tls
            #  name: certificate
            #  #subPath: crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1-node-port/tls/
            #  subPath: peers/peer0.org1/tls
            - mountPath: /host/var/run/
              name: run
        - image: docker:dind
          name: dind
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/docker
              mountPropagation: "Bidirectional"
              name: docker-graph-storage
      volumes:
        - hostPath:
            path: /root/Hyperledger_K8S_POC/crypto-config/peerOrganizations/org1-node-port/peers/peer0.org1-node-port/msp
          name: peer0-org1-msp-volume
        - hostPath:
            path: /root/Hyperledger_K8S_POC/channel-artifacts/genesis.block
          name: genesis-block-volume
        - name: run
          hostPath:
            path: /var/run
        - name: docker-graph-storage 
          emptyDir: {}
        - name: couchdb-storage
          persistentVolumeClaim:
            claimName: couchdb-volume-claim
# kubectl create secret generic couch_db_secret --from-literal COUCHDB_PASSWORD=couchdb