apiVersion: v1
kind: Service
metadata:
  name: peer0-node-port
spec:
  type: NodePort
  selector:
    component: peer0
  ports:
    - name: couchdb
      port: 5984
      targetPort: 5984
      nodePort: 31521
    - name: peer1-external-listening-endpoint
      port: 7051
      targetPort: 7051
      nodePort: 31522
    - name: peer1-chaincode-listening-endpoint
      port: 7052
      targetPort: 7052
      nodePort: 31523
    - name: peer1-port3
      port: 7053
      targetPort: 7053
      nodePort: 31524
